name: Run Cron Job

on:
  schedule:
    - cron: '30 18 * * *' # 12 AM IST (UTC+5:30), 6:30 PM UTC

jobs:
  cron-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cron Job to Update LeetCode Stats
        run: curl -X GET 'https://leetcode-new-backend.onrender.com/update' # Replace with your deployed URL endpoint
